FROM alpine:latest
MAINTAINER Nat Weerawan <@nazt>

RUN apk update && apk add --update darkhttpd
RUN mkdir -p /home/www
RUN rm -rf /var/cache/apk/*

COPY ./www/ /home/www/
ADD ./run.sh /root/run.sh 

EXPOSE 80

CMD ["/root/run.sh"]
