FROM resin/raspberry-pi2-alpine
MAINTAINER Nat Weerawan <@nazt>

RUN apk update
RUN apk add --update openssl
RUN apk add ca-certificates
RUN update-ca-certificates
RUN apk add --update darkhttpd
RUN apk add --update jq

RUN mkdir -p /home/www
RUN rm -rf /var/cache/apk/*

COPY ./www/ /home/www/
ADD ./run.sh /root/run.sh 

EXPOSE 8080

CMD ["/root/run.sh"]
